name: Build Android AAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install gomobile
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin

          mkdir -p $HOME/work
          cd $HOME/work

          go mod init temp

          go get golang.org/x/mobile@v0.0.0-20240104190950-8578da9835fd

          go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20240104190950-8578da9835fd
          go install golang.org/x/mobile/cmd/gobind@v0.0.0-20240104190950-8578da9835fd

          gomobile init

      - name: Build AAR
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin

          gomobile bind \
            -androidapi=21 \
            -target=android \
            -o snowflake.aar .

      - uses: actions/upload-artifact@v4
        with:
          name: snowflake-aar
          path: snowflake.aar
