name: Build Android AAR

on:
  push:
    branches:
      - main # نام برنچ اصلی خود را اینجا بررسی کنید (ممکن است master باشد)
  workflow_dispatch: # این امکان را می‌دهد که اکشن را به صورت دستی هم اجرا کنید

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # می‌توانید نسخه Go مورد نیاز خود را تغییر دهید

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # جاوا برای ساخت فایل‌های اندرویدی الزامی است

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          gomobile init

      - name: Build AAR
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          
          # اضافه کردن وابستگی‌ها
          go get -tool golang.org/x/mobile/cmd/gobind
          go mod tidy
          
          # ساخت فایل AAR
          gomobile bind -target=android -androidapi=21 -o snowflake.aar .

      - name: Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snowflake-aar
          path: snowflake.aar
