name: Android Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Generate go.sum
        run: |
          cd go/snowflakeandroid
          go mod tidy

      - name: Show Go files
        run: |
          cd go/snowflakeandroid
          ls -la

      - name: Build Go package
        run: |
          cd go/snowflakeandroid
          go build ./...
