name: Android Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install gomobile
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin

          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest

          go get golang.org/x/mobile/bind

          gomobile init

      - name: Build AAR
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gomobile bind -androidapi=21 -target=android -o snowflake.aar .